import Main from "@/src/components/Main";
import Head from "next/head";
import { Banner } from "@/src/components/Banner/Banner";
import { Footer } from "@/src/components/Footer/Footer";

export default function Home() {
    return (
        <div>
            <Head>
                <title>0807-tech</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="pt-20 w-full mx-auto">
                <Banner />
                <Footer />
            </div>
        </div>
    );
}
